In [3]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
%pip install numpy

In [8]:
#1d
data = np.array([21,22,23,24,25])
print(data)
print(data[2])
print(data.shape)
print(data.ndim)

[21 22 23 24 25]
23
(5,)
1


In [9]:
#2d
data = np.array([[21,22,23,24],[25,26,27,28],[29,30,31,32]])
print(data)
print(data[1][2])
print(data.shape)
print(data.ndim)

[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
27
(3, 4)
2


In [14]:
#3d
data = np.array([[[21,22,23,24],[25,26,27,28],[29,30,31,32]],
                 [[210,220,230,240],[250,260,270,280],[290,300,310,320]]
                ])
print(data)
print(data.shape)
print(data.ndim)
print(data[1][1][0]) #array,row,column
print(data[0][1][0])

[[[ 21  22  23  24]
  [ 25  26  27  28]
  [ 29  30  31  32]]

 [[210 220 230 240]
  [250 260 270 280]
  [290 300 310 320]]]
(2, 3, 4)
3
250
25


In [18]:
data = [21,22,23,24,25,26,27,28]
print(type(data))
arr = np.array(data)
print(type(arr))
print(data)
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[21, 22, 23, 24, 25, 26, 27, 28]
[21 22 23 24 25 26 27 28]


In [19]:
data = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(data)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [ ]:
print(data[1][2])